'use strict';
const D=window.LESSON, KEY='respiratoir-oefenen-v1';
const options=['Luchtwegen hoog','Luchtwegen laag','Ademprikkel','Ademarbeid / adempomp','Diffusie en alveolaire gaswisseling','Pulmonale microcirculatie'];
const cases=[{id:1,title:'Rond de uitleiding',desc:'Milan · 36 jaar · ASA I',ids:[1,2,3]},{id:2,title:'Laparoscopische chirurgie',desc:'Nora · 44 jaar · ASA II',ids:[4,5,6]},{id:3,title:'De heupoperatie',desc:'Rob · 68 jaar · ASA II, met een aparte verdiepende variant',ids:[7,8]}];
let state={};let storageOK=true;
try{state=JSON.parse(localStorage.getItem(KEY)||'{}');if(!state||typeof state!=='object'||Array.isArray(state))state={}}catch{state={};storageOK=false}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const main=document.querySelector('main');
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{storageOK=false}if(!storageOK)document.querySelector('#storage-note').textContent='Opslaan is niet beschikbaar. Je antwoorden blijven alleen behouden zolang deze pagina open is.'}
function done(id){return !!state[id]?.submitted}
function count(){return D.scenarios.filter(s=>done(s.id)).length}
function home(){return `<div class="intro"><div class="eyebrow">Oefenen · Respiratoir systeem</div><h1>Waar begint het probleem?</h1><p>Onderzoek acht situaties tijdens anesthesie. Kies het primaire aandachtspunt, onderbouw je keuze en vergelijk je redenering met het antwoordmodel.</p></div><div class="case-grid">${cases.map(c=>`<section class="case-card"><span class="number">0${c.id}</span><h2>${c.title}</h2><p>${c.desc}</p><p class="subtle">${c.ids.length} onafhankelijke scenario’s · ${c.ids.filter(done).length} afgerond</p><a class="button" href="#casus-${c.id}">Open casus ${c.id}</a></section>`).join('')}</div><p class="subtle">${count()} van 8 scenario’s afgerond</p><progress value="${count()}" max="8" aria-label="Voortgang"></progress><div class="notice">Elk scenario is een afzonderlijke variant. Neem complicaties en meetwaarden uit een vorige variant niet mee.</div><details><summary>Leerdoelen en werkwijze</summary><ul>${D.goals.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p>Reken op ongeveer 5 minuten per scenario. De keuzevraag wordt automatisch nagekeken. Open antwoorden vergelijk je zelf met het model; hiervoor krijg je geen automatisch cijfer.</p></details>`}
function casePage(id){const c=cases.find(x=>x.id===id);if(!c)return home();return `<a href="#">Alle casussen</a><div class="eyebrow">Casus ${id}</div><h1>${c.title}</h1><p>${c.desc}</p><div class="notice">Kies een scenario. Iedere variant begint opnieuw met de eigen uitgangssituatie.</div><ul class="scenario-list">${c.ids.map(n=>{const s=D.scenarios[n-1];return `<li><a href="#scenario-${n}">${n}. ${esc(s.title)}</a><span class="subtle">${n===8?'Verdieping · ':''}${done(n)?'Afgerond':'Nog te oefenen'}</span></li>`}).join('')}</ul>`}
function feedback(s,a){return `<section class="feedback" id="feedback" tabindex="-1"><div class="eyebrow">Antwoord en nabespreking</div><h2 class="result ${a.choice===s.answer?'correct':'incorrect'}">${a.choice===s.answer?'Je keuze past bij het antwoordmodel':'Vergelijk je keuze met het antwoordmodel'}</h2><p>Jouw keuze: <strong>${esc(options[a.choice])}</strong></p><p><strong>Primair probleem:</strong> ${esc(s.feedback['Primair probleem'])}</p><div class="notice">${esc(s.feedback.Kernfeedback)}</div>${['Verklaring','Interventies','Monitoring en herstel','Relatie met anesthesietechniek'].map(k=>`<details ${k==='Verklaring'?'open':''}><summary>${k}</summary><p>${esc(s.feedback[k])}</p></details>`).join('')}<details><summary>Vergelijk met jouw open antwoorden</summary>${s.questions.map((q,i)=>`<h3>${esc(q)}</h3><p class="answer-copy">${esc(a.notes?.[i]||'Geen antwoord ingevuld.')}</p>`).join('')}</details><p class="subtle">De open antwoorden zijn niet automatisch beoordeeld. Controleer of je het mechanisme, de eerste acties en de betekenis van monitoring kunt uitleggen.</p><div class="actions"><button class="secondary" id="retry">Dit scenario opnieuw</button><a class="button" href="${s.id<8?'#scenario-'+(s.id+1):'#overzicht'}">${s.id<8?'Volgend scenario':'Bekijk je overzicht'}</a></div></section>`}
function scenarioPage(id){const s=D.scenarios.find(x=>x.id===id);if(!s)return home();const a=state[id]||{notes:[]};const c=cases[s.case-1];return `<div class="layout"><aside aria-label="Scenario’s in deze casus"><h2>Casus ${s.case}</h2>${c.ids.map(n=>`<a href="#scenario-${n}" ${n===id?'aria-current="page"':''}>${n}. ${esc(D.scenarios[n-1].title)}${done(n)?' · Afgerond':''}</a>`).join('')}<a href="#">Alle casussen</a></aside><article class="panel"><div class="eyebrow">Scenario ${id} van 8</div><h1>${esc(s.title)}</h1>${id===8?'<p class="tag">Verdieping buiten ASA I/II</p>':''}<p class="subtle">Onafhankelijke variant · ongeveer 5 minuten</p><div class="patient scenario-text">${s.text.map(t=>`<p>${esc(t)}</p>`).join('')}</div>${a.submitted?feedback(s,a):`<form id="exercise"><fieldset><legend>Waar zit op dit moment het primaire probleem?</legend><div class="options">${options.map((o,i)=>`<label class="option"><input type="radio" name="primary" value="${i}" required ${a.choice===i?'checked':''}><span>${o}</span></label>`).join('')}</div></fieldset><p class="subtle">Luchtwegen hoog en laag zijn twee onderdelen van hetzelfde klinische aandachtspunt. Kies wat in deze fase primair verstoord is.</p>${s.questions.map((q,i)=>`<label class="question" for="note-${i}">${esc(q)}</label><textarea id="note-${i}" name="note-${i}" placeholder="Beschrijf je redenering…">${esc(a.notes?.[i]||'')}</textarea>`).join('')}<p class="subtle">Schrijf eerst je redenering op. Na bevestigen verschijnt de feedback.</p><div class="actions"><button type="submit">Bevestig en bekijk feedback</button></div></form>`}</article></div>`}
function overview(){return `<div class="eyebrow">Jouw voortgang</div><h1>${count()} van 8 scenario’s afgerond</h1><p>Dit overzicht toont welke oefeningen je hebt ingediend. Het is geen beoordeling van je volledige klinische redenering.</p><progress value="${count()}" max="8" aria-label="Afgeronde scenario’s"></progress><ul class="scenario-list">${D.scenarios.map(s=>`<li><a href="#scenario-${s.id}">${s.id}. ${esc(s.title)}</a><span class="subtle">${done(s.id)?(state[s.id].choice===s.answer?'Keuze correct · feedback beschikbaar':'Keuze herzien · feedback beschikbaar'):'Nog niet afgerond'}</span></li>`).join('')}</ul><button class="secondary" id="reset">Wis mijn antwoorden en voortgang</button>`}
function reference(){return `<div class="eyebrow">Naslag</div><h1>De vijf aandachtspunten</h1><p>Luchtwegen hoog en laag vallen samen onder één aandachtspunt.</p>${[['Luchtwegen','Kan lucht ongehinderd passeren? Onderscheid hoge en lage luchtwegen.'],['Ademprikkel','Geeft het ademcentrum voldoende centrale aansturing voor ventilatie?'],['Ademarbeid / adempomp','Kan de adempomp voldoende ventilatie leveren bij de aanwezige weerstand en compliantie?'],['Diffusie en alveolaire gaswisseling','Deze oefening gebruikt een brede lescategorie. Shunt en V/Q-mismatch zijn andere mechanismen dan een zuivere diffusiestoornis.'],['Pulmonale microcirculatie','Bereikt voldoende bloed de geventileerde alveoli?']].map(([a,b])=>`<h2>${a}</h2><p>${b}</p>`).join('')}<div class="notice">De casussen en meetwaarden zijn fictieve didactische voorbeelden. Oefen interventies vanuit de rol van anesthesiemedewerker, met de anesthesioloog en volgens het lokale protocol.</div><h2>Bronnen uit het lesdocument</h2><div class="sources">${D.sources.map(t=>{let m=t.match(/https?:\/\/\S+/);return `<p>${m?esc(t.slice(0,m.index))+`<a target="_blank" rel="noopener noreferrer" href="${esc(m[0])}">${esc(m[0])}</a>`:esc(t)}</p>`}).join('')}</div><p class="subtle">Inhoud overgenomen uit ‘Respiratoir systeem — drie casussen en acht scenario’s met studentvragen en antwoordmodellen’. De bronnenlijst is overgenomen uit het aangeleverde document.</p>`}
function render(){const h=location.hash.slice(1),m=h.match(/^(casus|scenario)-(\d+)$/);main.innerHTML=m?(m[1]==='casus'?casePage(+m[2]):scenarioPage(+m[2])):h==='overzicht'?overview():h==='uitleg'?reference():home();const id=m?.[1]==='scenario'?+m[2]:null;const form=document.querySelector('#exercise');if(form){const draft=()=>{state[id]={choice:form.elements.primary.value===''?null:Number(form.elements.primary.value),notes:[0,1,2].map(i=>form.elements['note-'+i].value),submitted:false};save()};form.addEventListener('input',draft);form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;draft();state[id].submitted=true;save();render();document.querySelector('#feedback').focus()})}document.querySelector('#retry')?.addEventListener('click',()=>{delete state[id];save();render();main.focus()});document.querySelector('#reset')?.addEventListener('click',()=>{if(confirm('Alle antwoorden en voortgang in deze browser wissen?')){state={};save();render()}});if(!storageOK)save()}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);main.focus()});render();
